version: '3.8'

services:
  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_pass
    ports:
      - "5433:5432"
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak-gestiup
    image: quay.io/keycloak/keycloak:25.0.1
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - keycloak-postgres
    restart: always

volumes:
  keycloak-postgres-data:
